FROM php:8.2-fpm-bullseye
#FROM ubuntu:20.04
#FROM node:12.18.1
#RUN apt-get clean && apt-get update
RUN apt -yqq update
RUN apt -yqq install libxml2-dev
RUN apt-get update && apt-get install -y  \
      apt-utils \
      libpq-dev \
      libpng-dev \
      libzip-dev \
      zip unzip \
      git && \
      docker-php-ext-install pdo_mysql && \
      docker-php-ext-install bcmath && \
      docker-php-ext-install gd && \
      docker-php-ext-install zip && \
      apt-get clean && \
      rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
# RUN apt-get update && apt-get upgrade -y && \
 #         apt-get install -y nodejs --fix-missing
         # npm run

COPY ./_docker/app/php.ini /usr/local/etc/php/conf.d/php.ini

# Install Node
COPY package*.json ./
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y \
        nodejs \
    && npm i npm@latest -g



#Install composer
ENV COMPOSER_ALLOW_SUPERUSER=1
RUN curl -sS https://getcomposer.org/installer | php -- \
    --filename=composer \
    --install-dir=/usr/local/bin

#RUN npm install --quiet


WORKDIR /var/www

#CMD npm start
